### PR TITLE
Make module compatible with both Debian and other Unix OSs

### PR DESCRIPTION
**Pull request by markasammut**

### CODE REVIEW

**Comment by markasammut** [comment]
@pegasd are you able to fix the spec and acceptance tests for this enhancement to be merged? Current module is only compatible with Debian variants, this makes it compatible with Redhat. Thanks!

**Comment by pegasd** [comment]
Hey there, @markasammut !
Thanks for the interest in my module. I appreciate the PR.

I believe using `params.pp` is an outdated approach to handling multiple OS types. I can, however, make it work with data-in-modules. How about starting an issue and discussing details there?

Start with whichever version of RedHat you're using, so we can test against it.

**Comment by markasammut** [comment]
Hi @pegasd , thanks for your feedback. I'm not very familiar with "data-in-modules". We are currently using a variety of RHEL6,7 and starting to test out RHEL8. On all versions the service name should be incrond. Care to help in making the necessary changes?

**Comment by pegasd** [comment]
@markasammut , let's discuss the implementation in #11.

I'll close this PR and start a new branch with the changes we need to implement.

**Pull request closed without merging**
